#!/usr/bin/env php
<?php
set_time_limit(0);

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;

$lame = new Lame\Kernel();
$lame->run();
